// <auto-generated />
using System;
using FitnessClub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessClub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250709121912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessClub.Domain.Entities.MembershipPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e356bb37-2be5-4ad6-9a66-339e4f10094a"),
                            Description = "Абонемент на 1 месяц, чтобы познакомиться с клубом.",
                            DurationInMonths = 1,
                            Name = "Новичок"
                        },
                        new
                        {
                            Id = new Guid("3c1121e5-7282-4d1f-9d57-680b9e36462b"),
                            Description = "Стандартный абонемент на 1 месяц.",
                            DurationInMonths = 1,
                            Name = "Стандарт 1"
                        },
                        new
                        {
                            Id = new Guid("4bfb3e5e-9d54-40cd-9388-4ad78acdaef4"),
                            Description = "Выгодный абонемент на 3 месяца.",
                            DurationInMonths = 3,
                            Name = "Стандарт 3"
                        },
                        new
                        {
                            Id = new Guid("ac75452c-6ab6-42cc-9d24-b5e120984286"),
                            Description = "Полугодовой абонемент для регулярных занятий.",
                            DurationInMonths = 6,
                            Name = "Стандарт 6"
                        },
                        new
                        {
                            Id = new Guid("9ba1a5e7-35cc-4e91-93be-1fe2e27de326"),
                            Description = "Годовой абонемент с максимальной выгодой.",
                            DurationInMonths = 12,
                            Name = "Стандарт 12"
                        },
                        new
                        {
                            Id = new Guid("d86dec31-d099-43f0-b860-8976f44e50ff"),
                            Description = "Специальный абонемент для студентов на 3 месяца.",
                            DurationInMonths = 3,
                            Name = "Студенческий"
                        },
                        new
                        {
                            Id = new Guid("b5adb578-bc5d-4d48-a7f1-137185eb9661"),
                            Description = "Абонемент для посещений в утренние часы (c 6:00 до 12:00).",
                            DurationInMonths = 1,
                            Name = "Утренний"
                        },
                        new
                        {
                            Id = new Guid("78dcd9cd-2373-4cf0-8f64-f32464961788"),
                            Description = "Абонемент для посещений в дневные часы (c 12:00 до 17:00).",
                            DurationInMonths = 1,
                            Name = "Дневной"
                        });
                });

            modelBuilder.Entity("FitnessClub.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MembershipPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MembershipPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("FitnessClub.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessClub.Domain.Entities.MembershipPlan", b =>
                {
                    b.OwnsOne("FitnessClub.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("MembershipPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("MembershipPlanId");

                            b1.ToTable("Plans");

                            b1.WithOwner()
                                .HasForeignKey("MembershipPlanId");

                            b1.HasData(
                                new
                                {
                                    MembershipPlanId = new Guid("e356bb37-2be5-4ad6-9a66-339e4f10094a"),
                                    Amount = 3590m,
                                    Currency = "RUB"
                                },
                                new
                                {
                                    MembershipPlanId = new Guid("3c1121e5-7282-4d1f-9d57-680b9e36462b"),
                                    Amount = 3990m,
                                    Currency = "RUB"
                                },
                                new
                                {
                                    MembershipPlanId = new Guid("4bfb3e5e-9d54-40cd-9388-4ad78acdaef4"),
                                    Amount = 10990m,
                                    Currency = "RUB"
                                },
                                new
                                {
                                    MembershipPlanId = new Guid("ac75452c-6ab6-42cc-9d24-b5e120984286"),
                                    Amount = 19990m,
                                    Currency = "RUB"
                                },
                                new
                                {
                                    MembershipPlanId = new Guid("9ba1a5e7-35cc-4e91-93be-1fe2e27de326"),
                                    Amount = 35990m,
                                    Currency = "RUB"
                                },
                                new
                                {
                                    MembershipPlanId = new Guid("d86dec31-d099-43f0-b860-8976f44e50ff"),
                                    Amount = 8990m,
                                    Currency = "RUB"
                                },
                                new
                                {
                                    MembershipPlanId = new Guid("b5adb578-bc5d-4d48-a7f1-137185eb9661"),
                                    Amount = 2990m,
                                    Currency = "RUB"
                                },
                                new
                                {
                                    MembershipPlanId = new Guid("78dcd9cd-2373-4cf0-8f64-f32464961788"),
                                    Amount = 3290m,
                                    Currency = "RUB"
                                });
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessClub.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("FitnessClub.Domain.Entities.MembershipPlan", "MembershipPlan")
                        .WithMany()
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessClub.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessClub.Domain.Entities.User", b =>
                {
                    b.OwnsOne("FitnessClub.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("FitnessClub.Domain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name");

                            b1.Property<string>("Patronymic")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Patronymic");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Surname");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("FitnessClub.Domain.ValueObjects.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PasswordHash");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PasswordSalt");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("FitnessClub.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessClub.Domain.Entities.User", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
